[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = 'python -c "from spam.summing import add; assert add([1,2,3],[4,5,6]) == [5,7,9]"'
